
```shell
bigorilla@kristen:~/group_practice$ git add .
warning: adding embedded git repository: python_projects/from_kylieying/reference/flask-project-doggos
hint: You've added another git repository inside your current repository.
hint: Clones of the outer repository will not contain the contents of
hint: the embedded repository and will not know how to obtain it.
hint: If you meant to add a submodule, use:
hint: 
hint:   git submodule add <url> python_projects/from_kylieying/reference/flask-project-doggos
hint: 
hint: If you added this path by mistake, you can remove it from the
hint: index with:
hint: 
hint:   git rm --cached python_projects/from_kylieying/reference/flask-project-doggos
hint: 
hint: See "git help submodule" for more information.
bigorilla@kristen:~/group_practice$ git submodule add python_projects/from_kylieying/reference/flask-project-doggos
fatal: repo URL: 'python_projects/from_kylieying/reference/flask-project-doggos' must be absolute or begin with ./|../
bigorilla@kristen:~/group_practice$ git submodule add python_projects/from_kylieying/reference
fatal: repo URL: 'python_projects/from_kylieying/reference' must be absolute or begin with ./|../
bigorilla@kristen:~/group_practice$ git submodule add ./python_projects/from_kylieying/reference
Cloning into '/home/bigorilla/group_practice/reference'...
remote: Not Found
fatal: repository 'https://github.com/kristenqin/group_practice.git/python_projects/from_kylieying/reference/' not found
fatal: clone of 'https://github.com/kristenqin/group_practice.git/python_projects/from_kylieying/reference' into submodule path '/home/bigorilla/group_practice/reference' failed
bigorilla@kristen:~/group_practice$ git submodule add /home/bigorilla/group_practice/python_projects/from_kylieying/reference
fatal: repository '/home/bigorilla/group_practice/python_projects/from_kylieying/reference' does not exist
fatal: clone of '/home/bigorilla/group_practice/python_projects/from_kylieying/reference' into submodule path '/home/bigorilla/group_practice/reference' failed
bigorilla@kristen:~/group_practice$ git submodule add https://github.com/kying18/flask-project-doggos.git python_projects/from_kylieying/reference/flask-project-doggos
fatal: 'python_projects/from_kylieying/reference/flask-project-doggos' already exists in the index
bigorilla@kristen:~/group_practice$ git rm python_projects/from_kylieying/reference/flask-project-doggos
fatal: could not lookup name for submodule 'python_projects/from_kylieying/reference/flask-project-doggos'
bigorilla@kristen:~/group_practice$ git rm -r python_projects/from_kylieying/reference/flask-project-doggos
fatal: could not lookup name for submodule 'python_projects/from_kylieying/reference/flask-project-doggos'
bigorilla@kristen:~/group_practice$ git rm reference
fatal: pathspec 'reference' did not match any files
bigorilla@kristen:~/group_practice$ ls
'Initialization log.md'   datastructures_algorithms   python_projects   start.py        '计算机网络 chapt01.pdf'
 README.md                image                       solving.png       数据结构01.pdf   计算机网络02（了解即可.pdf
bigorilla@kristen:~/group_practice$ cd python_projects
bigorilla@kristen:~/group_practice/python_projects$ ls
from_kylieying  from_tomi
bigorilla@kristen:~/group_practice/python_projects$ cd from_kylieying
bigorilla@kristen:~/group_practice/python_projects/from_kylieying$ ls
__pycache__  reference  test  web.py
bigorilla@kristen:~/group_practice/python_projects/from_kylieying$ git add submodule https://github.com/kying18/flask-project-doggos.git ./reference
fatal: pathspec 'submodule' did not match any files
bigorilla@kristen:~/group_practice/python_projects/from_kylieying$ git submodule add https://github.com/kying18/flask-project-doggos.git ./reference
fatal: 'python_projects/from_kylieying/reference' already exists in the index
bigorilla@kristen:~/group_practice/python_projects/from_kylieying$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   __pycache__/web.cpython-310.pyc
        new file:   reference/flask-project-doggos
        new file:   test/__pycache__/flask-email-test.cpython-310.pyc
        new file:   test/flask-email-test.py
        new file:   web.py

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        deleted:    reference/flask-project-doggos

bigorilla@kristen:~/group_practice/python_projects/from_kylieying$ git add .
bigorilla@kristen:~/group_practice/python_projects/from_kylieying$ git submodule add https://github.com/kying18/flask-project-doggos.git ./reference
fatal: 'python_projects/from_kylieying/reference' already exists and is not a valid git repo
bigorilla@kristen:~/group_practice/python_projects/from_kylieying$ cd reference
bigorilla@kristen:~/group_practice/python_projects/from_kylieying/reference$ git init
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint:   git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint:   git branch -m <name>
Initialized empty Git repository in /home/bigorilla/group_practice/python_projects/from_kylieying/reference/.git/
bigorilla@kristen:~/group_practice/python_projects/from_kylieying/reference$ git submodule add https://github.com/kying18/flask-project-doggos.git ./reference
Cloning into '/home/bigorilla/group_practice/python_projects/from_kylieying/reference/reference'...
remote: Enumerating objects: 25, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 25 (delta 2), reused 13 (delta 1), pack-reused 0
Receiving objects: 100% (25/25), 339.25 KiB | 180.00 KiB/s, done.
Resolving deltas: 100% (2/2), done.
bigorilla@kristen:~/group_practice/python_projects/from_kylieying/reference$ git status
On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
        new file:   .gitmodules
        new file:   reference

bigorilla@kristen:~/group_practice/python_projects/from_kylieying/reference$ git commit -m "add module to practice buidling projects in python"
[master (root-commit) 9002d79] add module to practice buidling projects in python
 2 files changed, 4 insertions(+)
 create mode 100644 .gitmodules
 create mode 160000 reference
bigorilla@kristen:~/group_practice/python_projects/from_kylieying/reference$ git push
fatal: No configured push destination.
Either specify the URL from the command-line or configure a remote repository using

    git remote add <name> <url>

and then push using the remote name

    git push <name>

bigorilla@kristen:~/group_practice/python_projects/from_kylieying/reference$ cd ../
bigorilla@kristen:~/group_practice/python_projects/from_kylieying$ cd ../
bigorilla@kristen:~/group_practice/python_projects$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   from_kylieying/__pycache__/web.cpython-310.pyc
        new file:   from_kylieying/test/__pycache__/flask-email-test.cpython-310.pyc
        new file:   from_kylieying/test/flask-email-test.py
        new file:   from_kylieying/web.py

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        from_kylieying/reference/

bigorilla@kristen:~/group_practice/python_projects$ git add .
warning: adding embedded git repository: python_projects/from_kylieying/reference
hint: You've added another git repository inside your current repository.
hint: Clones of the outer repository will not contain the contents of
hint: the embedded repository and will not know how to obtain it.
hint: If you meant to add a submodule, use:
hint: 
hint:   git submodule add <url> python_projects/from_kylieying/reference
hint: 
hint: If you added this path by mistake, you can remove it from the
hint: index with:
hint: 
hint:   git rm --cached python_projects/from_kylieying/reference
hint: 
hint: See "git help submodule" for more information.
```



```shell
bigorilla@kristen:~/group_practice/python_projects$ git rm --cached ./from_kylieying/reference
error: the following file has staged content different from both the
file and the HEAD:
    python_projects/from_kylieying/reference
(use -f to force removal)
bigorilla@kristen:~/group_practice/python_projects$ git rm -f --cached ./from_kylieying/reference
rm 'python_projects/from_kylieying/reference'
bigorilla@kristen:~/group_practice/python_projects$ ls
from_kylieying  from_tomi
bigorilla@kristen:~/group_practice/python_projects$ mkdir reference
bigorilla@kristen:~/group_practice/python_projects$ git submodule add https://github.com/kying18/flask-project-doggos.git ./from_kylieying/reference
Cloning into '/home/bigorilla/group_practice/python_projects/from_kylieying/reference'...
remote: Enumerating objects: 25, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 25 (delta 2), reused 13 (delta 1), pack-reused 0
Receiving objects: 100% (25/25), 339.25 KiB | 277.00 KiB/s, done.
Resolving deltas: 100% (2/2), done.
bigorilla@kristen:~/group_practice/python_projects$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   ../.gitmodules
        new file:   from_kylieying/__pycache__/web.cpython-310.pyc
        new file:   from_kylieying/reference
        new file:   from_kylieying/test/__pycache__/flask-email-test.cpython-310.pyc
        new file:   from_kylieying/test/flask-email-test.py
        new file:   from_kylieying/web.py

bigorilla@kristen:~/group_practice/python_projects$ git add .
bigorilla@kristen:~/group_practice/python_projects$ git commit -m "add a module to practice building projects in python"
[main e32638c] add a module to practice building projects in python
 6 files changed, 55 insertions(+)
 create mode 100644 .gitmodules
 create mode 100644 python_projects/from_kylieying/__pycache__/web.cpython-310.pyc
 create mode 160000 python_projects/from_kylieying/reference
 create mode 100644 python_projects/from_kylieying/test/__pycache__/flask-email-test.cpython-310.pyc
 create mode 100644 python_projects/from_kylieying/test/flask-email-test.py
 create mode 100644 python_projects/from_kylieying/web.py
bigorilla@kristen:~/group_practice/python_projects$ git push
Enumerating objects: 13, done.
Counting objects: 100% (13/13), done.
Delta compression using up to 8 threads
Compressing objects: 100% (10/10), done.
Writing objects: 100% (12/12), 2.98 KiB | 1016.00 KiB/s, done.
Total 12 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/kristenqin/group_practice.git
   b1b11b9..e32638c  main -> main
```



```shell
GnuTLS error -110: The TLS connection was non-properly terminated.
```

That just means that the peer just closed the socket and did not do a proper TLS shutdown. Some broken clients or servers do this. Assuming that this message relates to a data transfer you can usually ignore this because the transfer was finished anyway, so no data got lost.

https://stackoverflow.com/questions/32113065/gnutls-error-110-the-tls-connection-was-non-properly-terminated





```shell
bigorilla@kristen:~/group_practice/python_projects/from_tomi$ python3 email_sender.py
tomi$ python3 email_sender.py
^CTraceback (most recent call last):
  File "/home/bigorilla/group_practice/python_projects/from_tomi/email_sender.py", line 32, in <module>
    with smtplib.SMTP_SSL("smtp.gmail.com", 465, context = context) as smtp: #TODO: 弄清楚with这块代码是在干什么
  File "/usr/lib/python3.10/smtplib.py", line 1050, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout,
  File "/usr/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.10/smtplib.py", line 1056, in _get_socket
    new_socket = super()._get_socket(host, port, timeout)
  File "/usr/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
```

> email_sender.py
>
> 类似这种模拟客户端功能的 总是会在计算机网络上出现问题 
>
> 找到相关问题描述
>
> 进一步描述自己的问题



<div>
    <a img = "./assets/github_img.gif"> my living space</a>
</div>

`git push` 经常出现





<img src="20230218195638.assets/image-20230218204748822.png" alt="image-20230218204748822" style="zoom:150%;" />